spring.application.name=PayementWebApp
logging.level.org.springframework.web=INFO


spring.datasource.url=jdbc:mysql://localhost:3306/pay_my_buddy?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=SADFDSAsd234@#$
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect